### ISSUE TITLE
Support for profiling 

### ISSUE THREAD

**Issue by jaredledvina** [halyard/halyard#129]
Working on this now but `sudo /opt/halyard/repo/meta/halyard` takes too long to execute in my opinion, adding some basic profiling support to figure why it's taking >30 secs.

**Comment by akerl** [comment]
I'd bet it's the librarian stuffs, offhand?

**Comment by akerl** [comment]
For the actual puppet side, worth pointing to https://github.com/halyard/boxenprofiler , which it itself a fork of puppet profiler and which probably needs tweaking but would profile the puppet stuffs

**Comment by jaredledvina** [comment]
Yeah, looks like it's because librarian keeps trying to reinstall all the modules. The puppet runs itself is actually really fast. The puppet agent `--profile` option outputs some interesting things.

**Comment by akerl** [comment]
If memory serves, I looked for a way to make the librarian fetch smarter, and couldn't find anything obvious. If you can figure something out, I'll gleefully merge.

**Comment by jaredledvina** [comment]
Yep, that's next up on my list :)

**Comment by akerl** [comment]
I think this is solved now? (allowing profiling). Closing in favor of future issues w/ specific slow things to fix.
