### ISSUE TITLE
halyard 1.10 with Ubuntu 16.04 not working

### ISSUE THREAD

**Issue by rampatnaik** [halyard/halyard#171]
latest halyard 1.10 not supporting Ubuntu 16.04

down grade halyard version working fine on Ubuntu 16.04
getting java error with 1.10 not supporting Ubuntu 16.04

java : 1.8

Problems in Global:
! ERROR Unexpected exception: java.lang.IndexOutOfBoundsException:
  Index: 0, Size: 0

- Failed to deploy Spinnaker.

**Comment by akerl** [comment]
Howdy;

Is it possible that you meant to open this on https://github.com/spinnaker/halyard ?
