### ISSUE TITLE
Document how to calculate hashed_sp_platform_uuid

### ISSUE THREAD

**Issue by double16** [halyard/halyard#173]
Individual hiera configs use hashed_sp_platform_uuid as the filename. I can't find how to determine that number for a given host.

**Comment by akerl** [comment]
The value is defined here: https://github.com/halyard/puppet-halyard/blob/master/lib/facter/hashed_sp_platform_uuid.rb#L6

It sources from the `sp_platform_uuid` puppet fact and then SHA512’s that value.

The easiest way to fetch this is likely:

```
system_profiler SPHardwareDataType | awk ‘/UUID/ { print $3 }’ | tr -d ‘\n’ | sha512sum
```

**Comment by akerl** [comment]
Closing, I've switch to just using MAC addresses directly
